# Generated by Django 5.0.3 on 2024-10-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0002_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
