# Generated by Django 5.0.3 on 2024-10-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0004_alter_expense_amount_alter_goal_estimated_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
